### ISSUE TITLE
Add "chore:" prefix and "[skip ci]" suffix to commit messages

### ISSUE THREAD

**Issue by achingbrain** [ipfs/github-mgmt#10]
Auto-merged commits like [this one](https://github.com/ipfs/eslint-config-ipfs/commit/7c3c83e2a68b281e65f550c26875ece000477fc5) create releases in repos that release with every change to master (e.g. most JS repos).

Please can they have `[skip ci]` added to the end of their commit messages so that CI is skipped and releases are not created.

Also, adding `chore:` to the beginning of the message will ensure an appropriate entry is added to the changelog, where changelogs are generated.

**Comment by galargh** [comment]
Sorry, I missed this. Of course, that makes sense. Assigning myself and I'll get it done after IPFS Thing.

**Comment by galargh** [comment]
https://github.com/protocol/github-mgmt-template/pull/49 <- this should do it; I'll test it after the conference

**Comment by galargh** [comment]
Done! All future commits made by this automation will have commit messages similar to this one https://github.com/ipfs/eslint-config-ipfs/commit/190fd9f37afdbeba62d50ebc78762d9e67959e09
