### ISSUE TITLE
feat: Add "add to project" workflow to all GUI repos

### ISSUE THREAD

**Issue by SgtPooki** [ipfs/github-mgmt#21]
Action to add to all repos is https://github.com/ipfs/ipfs-desktop/blob/main/.github/workflows/auto-project.yml. 

See https://github.com/ipfs/github-mgmt/pull/4 for example of what it should look like (though in yaml, not json)

### Actions required
- [ ] chore: Create org-wide token for auto-project.yml workflow
- [ ] TBD

**Comment by galargh** [comment]
We've automated adding GUI issues to GUI project in https://github.com/galargh/.github/pull/27. This can thus be closed.
