### ISSUE TITLE
Label support

### ISSUE THREAD

**Issue by SgtPooki** [ipfs/github-mgmt#74]
I see https://github.com/ipfs/github-mgmt/blob/935b24ada609bd31f1bb17a1523caccd170aff23/scripts/src/actions/shared/add-label-to-all-repos.ts#L7-L12 but I don't see that it's used anywhere.

I also couldn't find label support in this repo at all. Is there a list of labels that we add to all repos and how do I propose adding a label to that list?

**Comment by galargh** [comment]
Hey, we don't have label support in GitHub Management yet. The script you linked to was only being used locally but I see I must have failed to commit the part that actually calls this function.

**Comment by galargh** [comment]
I created an issue for adding label support in the main github management repo - https://github.com/protocol/github-mgmt-template/issues/81. Let's have further conversations there. I'm going to close this one.
